title: Matteo's tech blog
email: rosati.matteo@gmail.com
description: >
  Hi there! My name is Matteo Rosati.
  I am an italian full-stack developer employed at H-ART, part
  of the AKQA network. I develop primarly in PHP and Javascript.
baseurl: ""
url: "https://mrosati84.github.io"
twitter_username: rosatimatteo
github_username:  mrosati84

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
