title: Matteo's tech blog
email: rosati.matteo@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hi there! My name is Matteo Rosati.
  I am an italian full-stack developer employed at H-ART, part
  of the AKQA network. I develop primarly in PHP and Javascript.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rosatimatteo
github_username:  mrosati84

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
